"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { TerminalPanel } from "@/components/TerminalPanel";
import {
  bootForkLabPod,
  installBrowserPodRuntimeErrorGuard,
  makeStorageKey,
  readTextFile,
  toUserFacingError,
  writeTextFile,
  type BrowserPodInstance,
  type UserFacingError,
} from "@/lib/browserpod";
import {
  variantArenaTask,
  variantDefinitions,
  variantIds,
  type GeneratedVariant,
  type VariantGenerationResponse,
  type VariantId,
} from "@/lib/llm/variantArenaSchema";
import {
  createVariantProjectFiles,
  getVariantFolder,
  sampleRepoDescriptor,
  variantPortById,
} from "@/lib/variantArenaProject";

type VariantStatus =
  | "queued"
  | "generating"
  | "generated"
  | "writing"
  | "installing"
  | "running"
  | "preview-ready"
  | "fallback"
  | "failed";

type VariantRun = {
  status: VariantStatus;
  terminal: string[];
  filesWritten: string[];
  previewUrl?: string;
  notes: string;
  runtime: "not-run" | "express" | "node-http";
};

type PortalEvent = {
  url: string;
  port: number;
};

type PodWithPortal = BrowserPodInstance & {
  onPortal?: (callback: (event: PortalEvent) => void) => void;
};

const initialRuns = createInitialRuns();

export default function VariantArenaPage() {
  const terminalRef = useRef<HTMLDivElement | null>(null);
  const podRef = useRef<BrowserPodInstance | null>(null);
  const terminalInstanceRef = useRef<unknown>(null);
  const [task, setTask] = useState(variantArenaTask);
  const [safeMode, setSafeMode] = useState(true);
  const [selectedVariantId, setSelectedVariantId] =
    useState<VariantId>("enterprise-trust");
  const [variants, setVariants] = useState<GeneratedVariant[]>([]);
  const [runs, setRuns] = useState<Record<VariantId, VariantRun>>(initialRuns);
  const [logs, setLogs] = useState<string[]>([
    "Ready. Generate variants to write acme-landing-page into BrowserPod.",
  ]);
  const [providerUsed, setProviderUsed] =
    useState<VariantGenerationResponse["provider"] | "pending">("pending");
  const [generationFallback, setGenerationFallback] = useState(false);
  const [status, setStatus] = useState<VariantStatus>("queued");
  const [portalEvents, setPortalEvents] = useState<PortalEvent[]>([]);
  const [connectorMessage, setConnectorMessage] = useState(
    "Built-in sample repo is active for this demo.",
  );
  const [error, setError] = useState<UserFacingError | null>(null);

  const isBusy = [
    "generating",
    "writing",
    "installing",
    "running",
  ].includes(status);
  const selectedVariant = useMemo(
    () => variants.find((variant) => variant.id === selectedVariantId),
    [selectedVariantId, variants],
  );

  useEffect(() => installBrowserPodRuntimeErrorGuard(), []);

  async function generateAndRun() {
    setError(null);
    setStatus("generating");
    setProviderUsed("pending");
    setGenerationFallback(false);
    setPortalEvents([]);
    setVariants([]);
    setRuns(
      variantIds.reduce((nextRuns, id) => {
        nextRuns[id] = {
          ...initialRuns[id],
          status: "generating",
          terminal: ["$ request variant generation"],
          notes: "Waiting for Gemini/Groq or deterministic fallback.",
        };
        return nextRuns;
      }, {} as Record<VariantId, VariantRun>),
    );
    setLogs([
      "$ variant-arena generate",
      `sampleRepo=${sampleRepoDescriptor.name}`,
      `demoSafeMode=${safeMode ? "on" : "off"}`,
    ]);

    if (terminalRef.current) {
      terminalRef.current.innerHTML = "";
    }

    try {
      const response = await fetch("/api/variant-arena/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          task,
          variants: variantIds,
        }),
      });

      if (!response.ok) {
        const detail = (await response.json()) as { message?: string };
        throw new Error(detail.message || "Variant generation failed.");
      }

      const payload = (await response.json()) as VariantGenerationResponse;
      setVariants(payload.variants);
      setProviderUsed(payload.provider);
      setGenerationFallback(payload.isFallback);
      setStatus("generated");
      setRuns(
        payload.variants.reduce((nextRuns, variant) => {
          nextRuns[variant.id] = {
            status: "generated",
            terminal: [
              `$ generated ${variant.id}`,
              `provider=${payload.provider}${payload.isFallback ? " fallback" : ""}`,
            ],
            filesWritten: variant.files.map((file) => file.path),
            notes: payload.isFallback
              ? "Deterministic fallback files generated because LLM generation was unavailable."
              : "Generated by server-side LLM route; files are ready for BrowserPod.",
            runtime: "not-run",
          };
          return nextRuns;
        }, createInitialRuns()),
      );
      setLogs((current) => [
        ...current,
        `$ generated ${payload.variants.length} variants`,
        `provider=${payload.provider}${payload.isFallback ? " fallback" : ""}`,
      ]);

      await writeAndRunVariants(payload.variants);
    } catch (caught) {
      setStatus("failed");
      const userError = toUserFacingError(caught);
      setError(userError);
      setLogs((current) => [...current, `Failed: ${userError.message}`]);
    }
  }

  async function rerunSelectedVariant() {
    if (!selectedVariant) return;
    setError(null);
    setPortalEvents([]);
    setLogs((current) => [
      ...current,
      `$ rerun selected variant ${selectedVariant.id}`,
    ]);
    await writeAndRunVariants(variants, [selectedVariant.id]);
  }

  async function writeAndRunVariants(
    nextVariants: GeneratedVariant[],
    explicitLiveIds?: VariantId[],
  ) {
    setStatus("writing");

    try {
      const pod = await bootForkLabPod(makeStorageKey("forklab-variants"));
      const terminal = await pod.createDefaultTerminal(terminalRef.current!);
      const waitForPortal = createPortalWatcher(pod);

      podRef.current = pod;
      terminalInstanceRef.current = terminal;

      setLogs((current) => [
        ...current,
        "$ boot BrowserPod variant arena",
        "$ create /forklab-variants",
      ]);

      await pod.createDirectory("/forklab-variants", { recursive: true });

      for (const variant of nextVariants) {
        await writeVariantProject(pod, variant, "express");
        const readBack = await readTextFile(
          pod,
          `${getVariantFolder(variant.id)}/public/index.html`,
        );
        updateRun(variant.id, (run) => ({
          ...run,
          status: "generated",
          terminal: [
            ...run.terminal,
            "$ wrote package.json",
            "$ wrote server.js",
            "$ wrote public/index.html",
            "$ wrote public/styles.css",
            `$ read public/index.html (${readBack.length} bytes)`,
          ],
          filesWritten: [
            "package.json",
            "server.js",
            "public/index.html",
            "public/styles.css",
            "README.md",
          ],
          notes:
            "Files written into BrowserPod. Runtime preview waits for selected execution.",
        }));
      }

      const liveIds =
        explicitLiveIds ??
        (safeMode ? [selectedVariantId] : nextVariants.map((variant) => variant.id));
      const liveVariants = nextVariants.filter((variant) =>
        liveIds.includes(variant.id),
      );

      for (const variant of liveVariants) {
        await runVariantRuntime(pod, terminal, waitForPortal, variant);
      }

      for (const variant of nextVariants) {
        if (!liveIds.includes(variant.id)) {
          updateRun(variant.id, (run) => ({
            ...run,
            status: "generated",
            terminal: [...run.terminal, "$ preview queued by Demo Safe Mode"],
            notes:
              "Generated and written into BrowserPod. Not run in safe mode.",
          }));
        }
      }

      setStatus(
        liveVariants.some((variant) => runs[variant.id]?.status === "failed")
          ? "failed"
          : "preview-ready",
      );
    } catch (caught) {
      setStatus("failed");
      const userError = toUserFacingError(caught);
      setError(userError);
      setLogs((current) => [...current, `Failed: ${userError.message}`]);
    }
  }

  async function writeVariantProject(
    pod: BrowserPodInstance,
    variant: GeneratedVariant,
    runtime: "express" | "http",
  ) {
    const folder = getVariantFolder(variant.id);
    const files = createVariantProjectFiles(
      variant,
      runtime === "express" ? "express" : "http",
    );

    updateRun(variant.id, (run) => ({
      ...run,
      status: "writing",
      terminal: [...run.terminal, `$ write ${folder}`],
      notes:
        runtime === "express"
          ? "Writing Express project files into BrowserPod."
          : "Writing built-in node:http fallback project into BrowserPod.",
      runtime: runtime === "express" ? "express" : "node-http",
    }));

    await pod.createDirectory(`${folder}/public`, { recursive: true });
    for (const file of files) {
      await writeTextFile(pod, `${folder}/${file.path}`, file.content);
    }
  }

  async function runVariantRuntime(
    pod: BrowserPodInstance,
    terminal: unknown,
    waitForPortal: (port: number, timeoutMs: number) => Promise<PortalEvent | null>,
    variant: GeneratedVariant,
  ) {
    const folder = getVariantFolder(variant.id);
    const port = variantPortById[variant.id];

    try {
      setStatus("installing");
      updateRun(variant.id, (run) => ({
        ...run,
        status: "installing",
        terminal: [...run.terminal, "$ npm install"],
        notes: "Installing Express inside BrowserPod.",
        runtime: "express",
      }));
      setLogs((current) => [
        ...current,
        `$ cd ${folder}`,
        "$ npm install",
      ]);

      await pod.run("npm", ["install"], {
        terminal,
        cwd: folder,
        echo: true,
      });

      await startServer(pod, terminal, waitForPortal, variant, "express");
    } catch (caught) {
      const message = caught instanceof Error ? caught.message : String(caught);
      setLogs((current) => [
        ...current,
        `Express install/run failed for ${variant.id}: ${message}`,
        "$ Express install failed; used built-in Node http fallback.",
      ]);
      updateRun(variant.id, (run) => ({
        ...run,
        status: "fallback",
        terminal: [
          ...run.terminal,
          `Express failed: ${message}`,
          "$ rewrite server.js with built-in node:http fallback",
        ],
        notes:
          "Express install failed; used built-in Node http fallback. Failure is shown honestly.",
        runtime: "node-http",
      }));

      await writeVariantProject(pod, variant, "http");
      await startServer(pod, terminal, waitForPortal, variant, "http");
    }
  }

  async function startServer(
    pod: BrowserPodInstance,
    terminal: unknown,
    waitForPortal: (port: number, timeoutMs: number) => Promise<PortalEvent | null>,
    variant: GeneratedVariant,
    runtime: "express" | "http",
  ) {
    const folder = getVariantFolder(variant.id);
    const port = variantPortById[variant.id];

    setStatus("running");
    updateRun(variant.id, (run) => ({
      ...run,
      status: runtime === "http" ? "fallback" : "running",
      terminal: [
        ...run.terminal,
        `$ PORT=${port} npm run start`,
      ],
      notes:
        runtime === "http"
          ? "Running built-in node:http fallback server."
          : "Running Express server and waiting for BrowserPod Portal.",
      runtime: runtime === "http" ? "node-http" : "express",
    }));
    setLogs((current) => [...current, `$ PORT=${port} npm run start`]);

    const outcomes: Array<
      Promise<
        | { kind: "portal"; portal: PortalEvent }
        | { kind: "timeout" }
        | { kind: "exited" }
        | { kind: "failed"; runError: unknown }
      >
    > = [
      waitForPortal(port, 15000).then((portal) =>
        portal
          ? ({ kind: "portal" as const, portal })
          : ({ kind: "timeout" as const }),
      ),
    ];

    const maybeRun = pod.run("npm", ["run", "start"], {
        terminal,
        cwd: folder,
        echo: true,
        env: [`PORT=${port}`],
      }) as unknown;

    if (isPromiseLike(maybeRun)) {
      outcomes.push(
        Promise.resolve(maybeRun)
          .then(() => ({ kind: "exited" as const }))
          .catch((runError: unknown) => ({ kind: "failed" as const, runError })),
      );
    }

    const outcome = await Promise.race(outcomes);

    if (outcome.kind === "failed") {
      throw outcome.runError;
    }

    if (outcome.kind === "portal") {
      updateRun(variant.id, (run) => ({
        ...run,
        status: runtime === "http" ? "fallback" : "preview-ready",
        previewUrl: outcome.portal.url,
        terminal: [
          ...run.terminal,
          `Portal ready: ${outcome.portal.url}`,
        ],
        notes:
          runtime === "http"
            ? "Node http fallback is running and BrowserPod Portal is ready."
            : "Express server is running and BrowserPod Portal is ready.",
      }));
      setLogs((current) => [
        ...current,
        `Portal ready for ${variant.id}: ${outcome.portal.url}`,
      ]);
      return;
    }

    updateRun(variant.id, (run) => ({
      ...run,
      status: "running",
      terminal: [
        ...run.terminal,
        outcome.kind === "timeout"
          ? "Portal was not reported before timeout."
          : "Server command exited before a portal was reported.",
      ],
      notes:
        outcome.kind === "timeout"
          ? "Server command was started, but BrowserPod did not report a portal URL."
          : "Server command exited before BrowserPod reported a portal URL.",
    }));
    setLogs((current) => [
      ...current,
      outcome.kind === "timeout"
        ? `No portal reported for ${variant.id} before timeout.`
        : `Server exited for ${variant.id} before portal was reported.`,
    ]);
  }

  function createPortalWatcher(pod: BrowserPodInstance) {
    const listeners = new Set<(event: PortalEvent) => void>();
    const podWithPortal = pod as PodWithPortal;

    if (typeof podWithPortal.onPortal === "function") {
      podWithPortal.onPortal((event) => {
        const portal = { url: event.url, port: event.port };
        setPortalEvents((current) => [...current, portal]);
        setLogs((current) => [
          ...current,
          `onPortal port=${portal.port} url=${portal.url}`,
        ]);
        listeners.forEach((listener) => listener(portal));
      });
    } else {
      setLogs((current) => [
        ...current,
        "BrowserPod onPortal callback is not available in this runtime.",
      ]);
    }

    return (port: number, timeoutMs: number) =>
      new Promise<PortalEvent | null>((resolve) => {
        const listener = (event: PortalEvent) => {
          if (event.port !== port) return;
          window.clearTimeout(timeout);
          listeners.delete(listener);
          resolve(event);
        };
        const timeout = window.setTimeout(() => {
          listeners.delete(listener);
          resolve(null);
        }, timeoutMs);

        listeners.add(listener);
      });
  }

  function updateRun(id: VariantId, updater: (run: VariantRun) => VariantRun) {
    setRuns((current) => ({
      ...current,
      [id]: updater(current[id]),
    }));
  }

  const comparisonRows = variantDefinitions.map((definition) => ({
    definition,
    run: runs[definition.id],
  }));

  return (
    <div className="variant-arena-shell">
      <header className="workbench-hero">
        <div>
          <p className="eyebrow">Variant Arena</p>
          <h1>Variant Arena</h1>
          <p className="muted-copy">
            One frontend task, multiple AI-generated variants, verified in
            BrowserPod.
          </p>
        </div>
        <div className="status-row">
          <span className="badge ok">BrowserPod file writes</span>
          <span className="badge info">Portal capture</span>
          <span className="badge warn">Safe mode default</span>
        </div>
      </header>

      <section className="proof-banner">
        AI-generated frontend variants are previews until BrowserPod runs them.
      </section>

      <div className="variant-top-grid">
        <section className="card stack">
          <div>
            <p className="eyebrow">Sample repo</p>
            <h2>{sampleRepoDescriptor.name}</h2>
            <p className="muted-copy">
              Type: {sampleRepoDescriptor.type}. Source:{" "}
              {sampleRepoDescriptor.source}. Future source:{" "}
              {sampleRepoDescriptor.futureSource}.
            </p>
          </div>
          <div className="artifact-list">
            {sampleRepoDescriptor.files.map((file) => (
              <div key={file}>
                <span>{file}</span>
                <strong>built-in</strong>
              </div>
            ))}
          </div>
        </section>

        <section className="card stack">
          <div>
            <p className="eyebrow">Repo source</p>
            <h2>Connector story</h2>
          </div>
          <div className="provider-controls">
            <button
              className="provider-option selected"
              type="button"
              onClick={() =>
                setConnectorMessage("Built-in sample repo is active for this demo.")
              }
            >
              Built-in sample repo
            </button>
            <button
              className="provider-option"
              type="button"
              onClick={() =>
                setConnectorMessage(
                  "GitHub MCP integration is planned. In production, ForkLab would import repo files/issues, generate variants, run them in BrowserPod, and attach preview/proof links to a PR.",
                )
              }
            >
              GitHub MCP
            </button>
            <button
              className="provider-option"
              type="button"
              onClick={() =>
                setConnectorMessage(
                  "ZIP upload is preview-only. Production ForkLab would unpack the repo, select frontend entry points, and run variants in BrowserPod.",
                )
              }
            >
              Upload ZIP
            </button>
          </div>
          <p className="info-callout">{connectorMessage}</p>
        </section>
      </div>

      <section className="card stack">
        <div className="variant-prompt-header">
          <div>
            <p className="eyebrow">Prompt</p>
            <h2>Generate frontend variants</h2>
          </div>
          <label className="badge" style={{ cursor: isBusy ? "not-allowed" : "pointer" }}>
            <input
              checked={safeMode}
              disabled={isBusy}
              onChange={(event) => setSafeMode(event.target.checked)}
              type="checkbox"
            />{" "}
            Demo Safe Mode: {safeMode ? "ON" : "OFF"}
          </label>
        </div>
        <div className="prompt-box">
          <textarea
            aria-label="Variant task prompt"
            value={task}
            onChange={(event) => setTask(event.target.value)}
          />
          <div className="prompt-actions">
            <button
              className="button primary"
              type="button"
              onClick={generateAndRun}
              disabled={isBusy || !task.trim()}
            >
              Generate variants
            </button>
            <button
              className="button"
              type="button"
              onClick={rerunSelectedVariant}
              disabled={isBusy || !variants.length}
            >
              Run selected live variant
            </button>
          </div>
          <p className="prompt-helper">
            Safe mode runs one real BrowserPod preview first and keeps the other
            generated variants queued for live preview.
          </p>
        </div>
        <div className="agent-model-grid">
          <div>
            <span>Provider used</span>
            <strong>{providerUsed}</strong>
          </div>
          <div>
            <span>Fallback mode</span>
            <strong>{generationFallback ? "Used" : "Not used"}</strong>
          </div>
        </div>
      </section>

      <section className="variant-card-grid">
        {variantDefinitions.map((definition) => {
          const variant = variants.find((item) => item.id === definition.id);
          const run = runs[definition.id];
          return (
            <article
              className={`variant-card${
                selectedVariantId === definition.id ? " selected" : ""
              }`}
              key={definition.id}
            >
              <div className="status-row">
                <span className={`badge ${statusTone(run.status)}`}>
                  {statusLabel(run.status)}
                </span>
                <span className="badge info">port {variantPortById[definition.id]}</span>
              </div>
              <button
                className="variant-card-title"
                type="button"
                onClick={() => setSelectedVariantId(definition.id)}
              >
                {variant?.title ?? definition.title}
              </button>
              <p>{variant?.summary ?? definition.goal}</p>
              <div className="agent-meta">
                <div>
                  <span>Files written</span>
                  <strong>
                    {run.filesWritten.length
                      ? `${run.filesWritten.length} files`
                      : "waiting"}
                  </strong>
                </div>
                <div>
                  <span>Runtime status</span>
                  <strong>{run.runtime}</strong>
                </div>
                <div>
                  <span>Preview URL</span>
                  <strong>
                    {run.previewUrl ? (
                      <a href={run.previewUrl} target="_blank" rel="noreferrer">
                        Open portal
                      </a>
                    ) : (
                      "not available yet"
                    )}
                  </strong>
                </div>
              </div>
              <pre className="agent-terminal">
                {run.terminal.slice(-8).join("\n")}
              </pre>
              <p className="muted-copy">{run.notes}</p>
            </article>
          );
        })}
      </section>

      <TerminalPanel
        title="/variant-arena · acme-landing-page"
        nativeRef={terminalRef}
        lines={logs}
      />

      <div className="variant-detail-grid">
        <section className="card stack">
          <div>
            <p className="eyebrow">Generated files</p>
            <h2>{selectedVariant?.title ?? "Select a variant"}</h2>
          </div>
          {selectedVariant ? (
            <div className="variant-files-grid">
              {selectedVariant.files.map((file) => (
                <div className="stack" key={file.path}>
                  <div className="status-row">
                    <span className="badge info">{file.path}</span>
                  </div>
                  <pre className="agent-code-block">{file.content}</pre>
                </div>
              ))}
            </div>
          ) : (
            <div className="run-empty-state">Generate variants to inspect files.</div>
          )}
        </section>

        <section className="truth-panel">
          <div>
            <p className="eyebrow">Reality panel</p>
            <h2>What is real?</h2>
          </div>
          <div className="truth-list">
            <TruthRow label="Real" text="BrowserPod boots in the browser." />
            <TruthRow label="Real" text="ForkLab writes package.json, server.js, HTML, CSS, and README files." />
            <TruthRow label="Real" text="At least one variant attempts npm install and npm run start." />
            <TruthRow label="Real" text="Terminal output is captured from BrowserPod." />
            <TruthRow label="Real" text="BrowserPod Portal links are shown when reported by onPortal." />
            <TruthRow label="Preview" text="GitHub MCP import, ZIP upload, full repo parsing, and production PR creation." />
          </div>
        </section>
      </div>

      <section className="truth-panel">
        <div>
          <p className="eyebrow">Comparison table</p>
          <h2>Variant proof summary</h2>
        </div>
        <div className="variant-comparison-table">
          <div className="variant-comparison-row comparison-head">
            <span>Variant</span>
            <span>Goal</span>
            <span>Files changed</span>
            <span>Runtime status</span>
            <span>Preview URL</span>
            <span>Notes</span>
          </div>
          {comparisonRows.map(({ definition, run }) => (
            <div className="variant-comparison-row" key={definition.id}>
              <strong>{definition.title}</strong>
              <span>{definition.goal}</span>
              <span>{run.filesWritten.join(", ") || "none yet"}</span>
              <span>{statusLabel(run.status)}</span>
              <span>
                {run.previewUrl ? (
                  <a href={run.previewUrl} target="_blank" rel="noreferrer">
                    {run.previewUrl}
                  </a>
                ) : (
                  "not available"
                )}
              </span>
              <span>{run.notes}</span>
            </div>
          ))}
        </div>
        {portalEvents.length ? (
          <div className="portal-list">
            {portalEvents.map((portal) => (
              <a
                className="badge ok"
                href={portal.url}
                key={`${portal.port}-${portal.url}`}
                rel="noreferrer"
                target="_blank"
              >
                Portal {portal.port}
              </a>
            ))}
          </div>
        ) : null}
      </section>

      {error ? (
        <section className="error-panel" aria-live="polite">
          <h3>{error.title}</h3>
          <p>{error.message}</p>
          <ul>
            {error.steps.map((step) => (
              <li key={step}>{step}</li>
            ))}
          </ul>
        </section>
      ) : null}
    </div>
  );
}

function TruthRow({ label, text }: { label: "Real" | "Preview"; text: string }) {
  return (
    <div className="truth-row">
      <span className={`badge ${label === "Real" ? "ok" : "info"}`}>{label}</span>
      <p>{text}</p>
    </div>
  );
}

function createInitialRuns(): Record<VariantId, VariantRun> {
  return variantIds.reduce((runs, id) => {
    runs[id] = {
      status: "queued",
      terminal: ["Queued for generation."],
      filesWritten: [],
      notes: "Waiting for generated files.",
      runtime: "not-run",
    };
    return runs;
  }, {} as Record<VariantId, VariantRun>);
}

function statusTone(status: VariantStatus) {
  if (status === "preview-ready") return "ok";
  if (status === "fallback" || status === "installing" || status === "running") {
    return "info";
  }
  if (status === "failed") return "fail";
  if (status === "queued") return "";
  return "warn";
}

function statusLabel(status: VariantStatus) {
  if (status === "preview-ready") return "preview ready";
  if (status === "fallback") return "fallback";
  return status.replace("-", " ");
}

function isPromiseLike(value: unknown): value is PromiseLike<unknown> {
  return Boolean(
    value &&
      (typeof value === "object" || typeof value === "function") &&
      "then" in value &&
      typeof (value as { then?: unknown }).then === "function",
  );
}
