import type {
  ArenaLiveFile,
  ArenaLiveVariant,
  ArenaLiveVariantId,
} from "@/lib/llm/arenaLiveSchema";

export const arenaLiveRepo = {
  name: "forklab-sandbox-acme-landing",
  stack: "Node.js + Express static frontend",
  source: "Built-in sandbox repo",
  futureConnectors: ["GitHub MCP", "Upload ZIP"],
} as const;

export const arenaLivePortById: Record<ArenaLiveVariantId, number> = {
  "enterprise-trust": 3000,
  "startup-conversion": 3001,
  "developer-minimal": 3002,
};

export function arenaLiveFolder(id: ArenaLiveVariantId) {
  return `/forklab-arena-live/${id}`;
}

export function createArenaLiveFiles(
  variant: ArenaLiveVariant,
  nonce: string,
  runtime: "express" | "node-http",
): Array<{ path: string; content: string }> {
  return [
    {
      path: "package.json",
      content:
        runtime === "express"
          ? createExpressPackageJson()
          : createNodeHttpPackageJson(),
    },
    {
      path: "server.js",
      content:
        runtime === "express"
          ? createExpressServer(variant.id)
          : createNodeHttpServer(variant.id),
    },
    {
      path: "README.md",
      content: createReadme(variant, runtime),
    },
    {
      path: "proof.js",
      content: createProofScript(nonce, variant.id),
    },
    ...variant.files,
  ];
}

function createExpressPackageJson() {
  return `${JSON.stringify(
    {
      name: arenaLiveRepo.name,
      version: "1.0.0",
      private: true,
      scripts: {
        start: "node server.js",
        test: "node proof.js",
      },
      dependencies: {
        express: "^4.18.2",
      },
    },
    null,
    2,
  )}
`;
}

function createNodeHttpPackageJson() {
  return `${JSON.stringify(
    {
      name: arenaLiveRepo.name,
      version: "1.0.0",
      private: true,
      scripts: {
        start: "node server.js",
        test: "node proof.js",
      },
      dependencies: {},
    },
    null,
    2,
  )}
`;
}

function createExpressServer(id: ArenaLiveVariantId) {
  return `const express = require("express");
const path = require("path");

const app = express();
const port = Number(process.env.PORT || ${arenaLivePortById[id]});
const publicDir = path.join(__dirname, "public");

app.use(express.static(publicDir));

app.get("/health", (_req, res) => {
  res.json({ ok: true, variant: "${id}", runtime: "express" });
});

app.listen(port, "0.0.0.0", () => {
  console.log("FORKLAB_ARENA_LIVE:${id}:express:listening:" + port);
});
`;
}

function createNodeHttpServer(id: ArenaLiveVariantId) {
  return `const fs = require("fs");
const http = require("http");
const path = require("path");

const port = Number(process.env.PORT || ${arenaLivePortById[id]});
const publicDir = path.join(__dirname, "public");
const mime = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
};

const server = http.createServer((req, res) => {
  const rawUrl = req.url === "/" ? "/index.html" : req.url || "/index.html";
  const safeUrl = path.normalize(rawUrl).replace(/^\\.\\.(\\/|\\\\|$)/, "");
  const filePath = path.join(publicDir, safeUrl);
  const ext = path.extname(filePath);

  fs.readFile(filePath, (error, data) => {
    if (error) {
      res.writeHead(404, { "content-type": "text/plain; charset=utf-8" });
      res.end("Not found");
      return;
    }

    res.writeHead(200, { "content-type": mime[ext] || "text/plain; charset=utf-8" });
    res.end(data);
  });
});

server.listen(port, "0.0.0.0", () => {
  console.log("FORKLAB_ARENA_LIVE:${id}:node-http:listening:" + port);
});
`;
}

function createProofScript(nonce: string, id: ArenaLiveVariantId) {
  return `const fs = require("fs");

const result = {
  variantId: "${id}",
  nonce: "${nonce}",
  status: "ok",
  command: "npm test",
  filesExpected: ["public/index.html", "public/styles.css"],
};

console.log("FORKLAB_VARIANT_NONCE:" + result.nonce);
fs.writeFileSync("proof-result.json", JSON.stringify(result, null, 2));
`;
}

function createReadme(variant: ArenaLiveVariant, runtime: "express" | "node-http") {
  return `# ${arenaLiveRepo.name}

Variant: ${variant.title}
Strategy: ${variant.strategy}
Audience: ${variant.audience}
Runtime: ${runtime}

This project was generated by ForkLab Arena Live and written into BrowserPod.
Only static HTML and CSS are generated by the LLM. ForkLab owns the commands.
`;
}

export function fileContent(files: ArenaLiveFile[], path: ArenaLiveFile["path"]) {
  return files.find((file) => file.path === path)?.content ?? "";
}
